import type { ScanReport } from '../scanner.js';
import { gradeIcon, severityIcon, categoryLabel, getVersion } from './helpers.js';

export function toMarkdown(report: ScanReport): string {
  const lines: string[] = [];
  const icon = gradeIcon(report.grade);
  const total = report.findings.length;
  const critical = report.findings.filter(f => f.severity === 'critical');
  const high = report.findings.filter(f => f.severity === 'high');
  const medium = report.findings.filter(f => f.severity === 'medium');
  const low = report.findings.filter(f => f.severity === 'low');

  lines.push(
    `${icon} **Grade ${report.grade}** · Score **${report.score}**/100 · ${report.filesScanned} files scanned`,
  );
  lines.push('');

  appendStrengths(lines, report, total);
  appendCriticalIssues(lines, critical, high);
  appendImprovements(lines, medium, low);
  appendCategoryBreakdown(lines, report);
  appendHotFiles(lines, report);
  appendRecommendations(lines, total, critical, high, medium, low);

  lines.push(`<sub>Generated by forge-ai-init v${getVersion()} · ${report.filesScanned} files · ${total} findings</sub>`);
  lines.push('');

  return lines.join('\n');
}

function appendStrengths(lines: string[], report: ScanReport, total: number): void {
  if (total === 0) {
    lines.push('### ✅ Strengths');
    lines.push('');
    lines.push('- No anti-patterns detected across all scanned files');
    lines.push('- Codebase follows governance best practices');
    lines.push('');
    return;
  }
  const cleanCats = report.summary.filter(c => c.count === 0);
  if (cleanCats.length > 0) {
    lines.push('### ✅ Strengths');
    lines.push('');
    for (const c of cleanCats) {
      lines.push(`- **${categoryLabel(c.category)}** — No issues found`);
    }
    lines.push('');
  }
}

function appendCriticalIssues(lines: string[], critical: unknown[], high: unknown[]): void {
  if (critical.length === 0 && high.length === 0) return;
  lines.push('### 🚨 Critical Issues');
  lines.push('');
  const urgent = [...(critical as { severity: string; rule: string; file: string; line: number; message: string }[]),
    ...(high as { severity: string; rule: string; file: string; line: number; message: string }[])].slice(0, 15);
  lines.push('| Severity | Rule | File | Issue |');
  lines.push('|:--------:|------|------|-------|');
  for (const f of urgent) {
    lines.push(`| ${severityIcon(f.severity)} ${f.severity} | \`${f.rule}\` | \`${f.file}:${f.line}\` | ${f.message} |`);
  }
  if (critical.length + high.length > 15) {
    lines.push('');
    lines.push(`> …and ${critical.length + high.length - 15} more critical/high findings`);
  }
  lines.push('');
}

function appendImprovements(lines: string[], medium: unknown[], low: unknown[]): void {
  if (medium.length === 0 && low.length === 0) return;
  lines.push('<details>');
  lines.push(`<summary><strong>⚠️ Improvements (${medium.length + low.length})</strong></summary>`);
  lines.push('');
  const items = [...(medium as { severity: string; rule: string; file: string; line: number; message: string }[]),
    ...(low as { severity: string; rule: string; file: string; line: number; message: string }[])].slice(0, 20);
  lines.push('| Severity | Rule | File | Issue |');
  lines.push('|:--------:|------|------|-------|');
  for (const f of items) {
    lines.push(`| ${severityIcon(f.severity)} ${f.severity} | \`${f.rule}\` | \`${f.file}:${f.line}\` | ${f.message} |`);
  }
  if (medium.length + low.length > 20) {
    lines.push('');
    lines.push(`> …and ${medium.length + low.length - 20} more`);
  }
  lines.push('');
  lines.push('</details>');
  lines.push('');
}

function appendCategoryBreakdown(lines: string[], report: ScanReport): void {
  if (report.summary.length === 0) return;
  const cats = report.summary.filter(c => c.count > 0);
  if (cats.length === 0) return;
  lines.push('<details>');
  lines.push('<summary><strong>📊 Category Breakdown</strong></summary>');
  lines.push('');
  lines.push('| Category | Findings | Critical | High | Health |');
  lines.push('|----------|:--------:|:--------:|:----:|:------:|');
  for (const cat of report.summary) {
    const health = cat.critical > 0 ? '🔴' : cat.high > 0 ? '🟠' : cat.count > 0 ? '🟡' : '🟢';
    lines.push(`| ${categoryLabel(cat.category)} | ${cat.count} | ${cat.critical} | ${cat.high} | ${health} |`);
  }
  lines.push('');
  lines.push('</details>');
  lines.push('');
}

function appendHotFiles(lines: string[], report: ScanReport): void {
  if (report.topFiles.length === 0) return;
  lines.push('<details>');
  lines.push(`<summary><strong>📁 Hot Files (${report.topFiles.length})</strong></summary>`);
  lines.push('');
  lines.push('| File | Findings | Worst Severity |');
  lines.push('|------|:--------:|:--------------:|');
  for (const f of report.topFiles.slice(0, 10)) {
    lines.push(`| \`${f.file}\` | ${f.count} | ${severityIcon(f.worst)} ${f.worst} |`);
  }
  lines.push('');
  lines.push('</details>');
  lines.push('');
}

function appendRecommendations(
  lines: string[], total: number, critical: unknown[], high: unknown[], medium: unknown[], low: unknown[],
): void {
  if (total === 0) return;
  lines.push('### 💡 Recommendations');
  lines.push('');
  if (critical.length > 0) {
    lines.push(`- **Fix ${critical.length} critical issue${critical.length === 1 ? '' : 's'} immediately** — these represent security vulnerabilities or dangerous patterns`);
  }
  if (high.length > 0) {
    lines.push(`- **Address ${high.length} high-priority finding${high.length === 1 ? '' : 's'}** — technical debt that compounds over time`);
  }
  if (medium.length + low.length > 0) {
    lines.push(`- **${medium.length + low.length} improvement${medium.length + low.length === 1 ? '' : 's'}** to consider for code quality`);
  }
  lines.push('- Run `npx forge-ai-init` to add governance rules and CI quality gates');
  lines.push('');
}
