import type { Rule } from '../scanner.js';

export const engineeringRules: Rule[] = [
  {
    pattern: /@ts-ignore|@ts-nocheck/g,
    category: 'engineering',
    severity: 'high',
    rule: 'ts-suppress',
    message: '@ts-ignore/@ts-nocheck suppresses type safety',
    extensions: ['.ts', '.tsx'],
  },
  {
    pattern: /readFileSync|writeFileSync|appendFileSync|mkdirSync/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'sync-io',
    message: 'Synchronous I/O blocks the event loop',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /key\s*=\s*\{?\s*(?:index|i|idx)\s*\}?/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'index-as-key',
    message: 'Array index as React key causes rendering bugs',
    extensions: ['.tsx', '.jsx', '.vue', '.svelte'],
  },
  {
    pattern: /!important/g,
    category: 'engineering',
    severity: 'low',
    rule: 'css-important',
    message: '!important overrides — hard to maintain',
  },
  {
    pattern: /console\.(log|debug|info)\s*\(/g,
    category: 'engineering',
    severity: 'low',
    rule: 'console-log',
    message: 'Console statement — use a logger or remove before production',
  },
  {
    pattern: /TODO|FIXME|HACK|XXX/g,
    category: 'engineering',
    severity: 'low',
    rule: 'todo-marker',
    message: 'TODO/FIXME marker — resolve before merging',
  },
  {
    pattern: /\.forEach\s*\([^)]*=>[^)]*\.push\b/g,
    category: 'engineering',
    severity: 'low',
    rule: 'forEach-push',
    message: 'forEach + push pattern — use map/filter/reduce instead',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /#\s*type:\s*ignore/g,
    category: 'engineering',
    severity: 'high',
    rule: 'type-ignore',
    message: '# type: ignore suppresses type checking — fix the underlying type issue',
    extensions: ['.py'],
  },
  {
    pattern: /import\s+\*/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'wildcard-import',
    message: 'Wildcard import pollutes namespace — import specific names',
    extensions: ['.py'],
  },
  {
    pattern: /def\s+\w+\([^)]*=\s*\[\]|def\s+\w+\([^)]*=\s*\{\}/g,
    category: 'engineering',
    severity: 'high',
    rule: 'mutable-default-arg',
    message: 'Mutable default argument — use None and create inside function',
    extensions: ['.py'],
  },
  {
    pattern: /^assert\s+/gm,
    category: 'engineering',
    severity: 'medium',
    rule: 'assert-in-production',
    message: 'assert is stripped with -O flag — use proper validation for production code',
    extensions: ['.py'],
  },
  {
    pattern: /import\s+_\s+"/g,
    category: 'engineering',
    severity: 'low',
    rule: 'go-blank-import',
    message: 'Blank import for side effects — document why with a comment',
    extensions: ['.go'],
  },
  {
    pattern: /todo!\s*\(|unimplemented!\s*\(/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'rust-todo-macro',
    message: 'todo!/unimplemented! panics at runtime — implement before shipping',
    extensions: ['.rs'],
  },
  {
    pattern: /allow\s*\(\s*(?:clippy::|unused|dead_code)/g,
    category: 'engineering',
    severity: 'low',
    rule: 'rust-allow-lint',
    message: 'Lint suppression — fix the warning instead of suppressing it',
    extensions: ['.rs'],
  },
];
