import type { Rule } from '../scanner.js';

export const engineeringRules: Rule[] = [
  {
    pattern: /@ts-ignore|@ts-nocheck/g,
    category: 'engineering',
    severity: 'high',
    rule: 'ts-suppress',
    message: '@ts-ignore/@ts-nocheck suppresses type safety',
    extensions: ['.ts', '.tsx'],
  },
  {
    pattern: /readFileSync|writeFileSync|appendFileSync|mkdirSync/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'sync-io',
    message: 'Synchronous I/O blocks the event loop',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /key\s*=\s*\{?\s*(?:index|i|idx)\s*\}?/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'index-as-key',
    message: 'Array index as React key causes rendering bugs',
    extensions: ['.tsx', '.jsx', '.vue', '.svelte'],
  },
  {
    pattern: /!important/g,
    category: 'engineering',
    severity: 'low',
    rule: 'css-important',
    message: '!important overrides — hard to maintain',
  },
  {
    pattern: /console\.(log|debug|info)\s*\(/g,
    category: 'engineering',
    severity: 'low',
    rule: 'console-log',
    message: 'Console statement — use a logger or remove before production',
  },
  {
    pattern: /TODO|FIXME|HACK|XXX/g,
    category: 'engineering',
    severity: 'low',
    rule: 'todo-marker',
    message: 'TODO/FIXME marker — resolve before merging',
  },
  {
    pattern: /\.forEach\s*\([^)]*=>[^)]*\.push\b/g,
    category: 'engineering',
    severity: 'low',
    rule: 'forEach-push',
    message: 'forEach + push pattern — use map/filter/reduce instead',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /#\s*type:\s*ignore/g,
    category: 'engineering',
    severity: 'high',
    rule: 'type-ignore',
    message: '# type: ignore suppresses type checking — fix the underlying type issue',
    extensions: ['.py'],
  },
  {
    pattern: /import\s+\*/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'wildcard-import',
    message: 'Wildcard import pollutes namespace — import specific names',
    extensions: ['.py'],
  },
  {
    pattern: /def\s+\w+\([^)]*=\s*\[\]|def\s+\w+\([^)]*=\s*\{\}/g,
    category: 'engineering',
    severity: 'high',
    rule: 'mutable-default-arg',
    message: 'Mutable default argument — use None and create inside function',
    extensions: ['.py'],
  },
  {
    pattern: /^assert\s+/gm,
    category: 'engineering',
    severity: 'medium',
    rule: 'assert-in-production',
    message: 'assert is stripped with -O flag — use proper validation for production code',
    extensions: ['.py'],
  },
  {
    pattern: /import\s+_\s+"/g,
    category: 'engineering',
    severity: 'low',
    rule: 'go-blank-import',
    message: 'Blank import for side effects — document why with a comment',
    extensions: ['.go'],
  },
  {
    pattern: /todo!\s*\(|unimplemented!\s*\(/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'rust-todo-macro',
    message: 'todo!/unimplemented! panics at runtime — implement before shipping',
    extensions: ['.rs'],
  },
  {
    pattern: /allow\s*\(\s*(?:clippy::|unused|dead_code)/g,
    category: 'engineering',
    severity: 'low',
    rule: 'rust-allow-lint',
    message: 'Lint suppression — fix the warning instead of suppressing it',
    extensions: ['.rs'],
  },
  {
    pattern: /\$:\s*\w+\s*=\s*\w+/g,
    category: 'engineering',
    severity: 'low',
    rule: 'svelte-reactive-assignment',
    message: 'Reactive declaration — ensure dependency tracking is intentional',
    extensions: ['.svelte'],
  },
  {
    pattern: /on:click\s*=\s*\{[^}]*(?:window|document)\./g,
    category: 'engineering',
    severity: 'medium',
    rule: 'svelte-global-dom-access',
    message: 'Direct DOM access in event handler — use Svelte actions or bind:this',
    extensions: ['.svelte'],
  },
  {
    pattern: /export\s+let\s+\w+\s*=\s*\[\]|export\s+let\s+\w+\s*=\s*\{\}/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'svelte-mutable-prop-default',
    message: 'Mutable default prop — shared reference between instances',
    extensions: ['.svelte'],
  },
  {
    pattern: /\$\$props/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'svelte-spread-props',
    message: '$$props breaks reactivity optimizations — declare props explicitly',
    extensions: ['.svelte'],
  },
  {
    pattern: /os\.Exit\s*\(/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'go-os-exit',
    message: 'os.Exit() skips deferred functions — return from main instead',
    extensions: ['.go'],
  },
  {
    pattern: /System\.(out|err)\.print(ln)?\s*\(/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'java-sysout',
    message: 'System.out/err.println — use a logging framework (SLF4J, Log4j)',
    extensions: ['.java'],
  },
  {
    pattern: /@SuppressWarnings\s*\(/g,
    category: 'engineering',
    severity: 'low',
    rule: 'java-suppress-warnings',
    message: '@SuppressWarnings hides issues — fix the warning instead',
    extensions: ['.java'],
  },
  {
    pattern: /new\s+Date\s*\(\s*\)|new\s+SimpleDateFormat\s*\(/g,
    category: 'engineering',
    severity: 'low',
    rule: 'java-legacy-date',
    message: 'Legacy Date/SimpleDateFormat — use java.time (LocalDate, DateTimeFormatter)',
    extensions: ['.java'],
  },
  {
    pattern: /\.printStackTrace\s*\(\s*\)/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'java-print-stacktrace',
    message: '.printStackTrace() — use a logger to capture exceptions',
    extensions: ['.java'],
  },
  {
    pattern: /@Suppress\s*\(/g,
    category: 'engineering',
    severity: 'low',
    rule: 'kotlin-suppress',
    message: '@Suppress hides issues — fix the warning instead',
    extensions: ['.kt', '.kts'],
  },
  {
    pattern: /TODO\s*\(|FIXME/g,
    category: 'engineering',
    severity: 'low',
    rule: 'kotlin-todo',
    message: 'TODO/FIXME marker — resolve before shipping',
    extensions: ['.kt', '.kts'],
  },
  {
    pattern: /\bprint\s*\(/g,
    category: 'engineering',
    severity: 'low',
    rule: 'python-print',
    message: 'print() in production — use logging module for structured output',
    extensions: ['.py'],
  },
  {
    pattern: /open\s*\([^)]*\)\s*(?!\s*as\b)/g,
    category: 'engineering',
    severity: 'medium',
    rule: 'python-open-no-context',
    message: 'File open without context manager — use `with open(...) as f:` to ensure cleanup',
    extensions: ['.py'],
  },
];
