import type { Rule } from '../scanner.js';

export const errorHandlingRules: Rule[] = [
  {
    pattern: /catch\s*\([^)]*\)\s*\{\s*\}/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'empty-catch',
    message: 'Empty catch block swallows errors silently',
  },
  {
    pattern:
      /catch\s*\([^)]*\)\s*\{\s*console\.(log|error|warn)\([^)]*\);\s*\}/g,
    category: 'error-handling',
    severity: 'medium',
    rule: 'console-only-catch',
    message: 'Catch block only logs — errors are lost',
  },
  {
    pattern: /except\s*:/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'bare-except',
    message: 'Bare except catches all exceptions including SystemExit — catch specific exceptions',
    extensions: ['.py'],
  },
  {
    pattern: /except\s+Exception\s*(?:as\s+\w+\s*)?:\s*(?:pass|\.\.\.)/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'except-pass',
    message: 'except Exception: pass silently swallows all errors',
    extensions: ['.py'],
  },
  {
    pattern: /if\s+err\s*!=\s*nil\s*\{\s*return\s+(?:nil,\s*)?err\s*\}/g,
    category: 'error-handling',
    severity: 'medium',
    rule: 'go-bare-error-return',
    message: 'Bare error return without wrapping — use fmt.Errorf or errors.Wrap for context',
    extensions: ['.go'],
  },
  {
    pattern: /panic\s*\(/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'go-panic',
    message: 'panic() crashes the program — return errors instead',
    extensions: ['.go'],
  },
  {
    pattern: /\.unwrap\s*\(\s*\)/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'rust-unwrap',
    message: '.unwrap() panics on error — use ? operator or handle the error',
    extensions: ['.rs'],
  },
  {
    pattern: /\.expect\s*\(/g,
    category: 'error-handling',
    severity: 'medium',
    rule: 'rust-expect',
    message: '.expect() panics with message — prefer ? operator in production code',
    extensions: ['.rs'],
  },
  {
    pattern: /\.lock\(\)\.unwrap\(\)/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'rust-lock-unwrap',
    message: 'Mutex lock().unwrap() panics on poison — handle the PoisonError',
    extensions: ['.rs'],
  },
  {
    pattern: /panic!\s*\(/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'rust-panic-macro',
    message: 'panic! crashes the program — return Result<T, E> instead',
    extensions: ['.rs'],
  },
  {
    pattern: /catch\s*\(\s*\w+\s+\w+\s*\)\s*\{\s*\}/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'java-empty-catch',
    message: 'Empty catch block swallows exceptions silently',
    extensions: ['.java'],
  },
  {
    pattern: /!!/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'kotlin-non-null-assertion',
    message: '!! non-null assertion crashes on null — use safe calls or elvis operator',
    extensions: ['.kt', '.kts'],
  },
  {
    pattern: /catch\s*\(\s*\w+\s*:\s*\w+\s*\)\s*\{\s*\}/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'kotlin-empty-catch',
    message: 'Empty catch block swallows exceptions silently',
    extensions: ['.kt', '.kts'],
  },
  {
    pattern: /\.catch\s*\(\s*\(\s*\)\s*=>\s*\{\s*\}\s*\)/g,
    category: 'error-handling',
    severity: 'high',
    rule: 'swallowed-promise',
    message: 'Empty .catch() swallows promise rejections silently',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
];
