import type { Rule } from '../scanner.js';

export const scalabilityRules: Rule[] = [
  {
    pattern: /import\s+\w+\s+from\s+['"]lodash['"]/g,
    category: 'scalability',
    severity: 'medium',
    rule: 'lodash-full-import',
    message: 'Full lodash import — use lodash/specific or lodash-es for tree-shaking',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs'],
  },
  {
    pattern: /var\s+\w+\s+sync\.Mutex/g,
    category: 'scalability',
    severity: 'medium',
    rule: 'go-global-mutex',
    message: 'Global mutex — consider channel-based concurrency or sync.RWMutex',
    extensions: ['.go'],
  },
  {
    pattern: /\.clone\s*\(\s*\)/g,
    category: 'scalability',
    severity: 'low',
    rule: 'rust-clone',
    message: '.clone() copies data — consider borrowing or Arc for shared ownership',
    extensions: ['.rs'],
  },
  {
    pattern: /\$:\s*\{[\s\S]*?fetch\s*\(/g,
    category: 'scalability',
    severity: 'medium',
    rule: 'svelte-reactive-fetch',
    message: 'Fetch in reactive block — may trigger on every state change, use onMount',
    extensions: ['.svelte'],
  },
  {
    pattern: /Thread\.sleep\s*\(/g,
    category: 'scalability',
    severity: 'medium',
    rule: 'java-thread-sleep',
    message: 'Thread.sleep blocks the thread — use ScheduledExecutorService or async',
    extensions: ['.java'],
  },
  {
    pattern: /runBlocking\s*\{/g,
    category: 'scalability',
    severity: 'high',
    rule: 'kotlin-run-blocking',
    message: 'runBlocking blocks the thread — use suspend functions or coroutineScope',
    extensions: ['.kt', '.kts'],
  },
  {
    pattern: /GlobalScope\.launch\s*\{/g,
    category: 'scalability',
    severity: 'high',
    rule: 'kotlin-global-scope',
    message: 'GlobalScope.launch leaks coroutines — use structured concurrency (viewModelScope, lifecycleScope)',
    extensions: ['.kt', '.kts'],
  },
  {
    pattern: /reflect\.\w+/g,
    category: 'scalability',
    severity: 'low',
    rule: 'go-reflect-usage',
    message: 'Reflection is slow and breaks type safety — use generics or interfaces',
    extensions: ['.go'],
  },
  {
    pattern: /Box::leak\s*\(/g,
    category: 'scalability',
    severity: 'medium',
    rule: 'rust-box-leak',
    message: 'Box::leak creates permanent memory leak — ensure intentional',
    extensions: ['.rs'],
  },
  {
    pattern: /time\.sleep\s*\(/g,
    category: 'scalability',
    severity: 'medium',
    rule: 'python-time-sleep',
    message: 'time.sleep() blocks the event loop — use asyncio.sleep in async code',
    extensions: ['.py'],
  },
];
