import type { Rule } from '../scanner.js';

export const securityRules: Rule[] = [
  {
    pattern:
      /(?:password|secret|api_key|apiKey|token)\s*[:=]\s*["'`][^"'`]{4,}["'`]/gi,
    category: 'security',
    severity: 'critical',
    rule: 'hardcoded-secret',
    message: 'Possible hardcoded secret — use environment variables',
  },
  {
    pattern: /dangerouslySetInnerHTML/g,
    category: 'security',
    severity: 'high',
    rule: 'unsafe-html',
    message: 'dangerouslySetInnerHTML — XSS risk',
    extensions: ['.tsx', '.jsx'],
  },
  {
    pattern: /eval\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'eval-usage',
    message: 'eval() — code injection risk',
  },
  {
    pattern: /innerHTML\s*=/g,
    category: 'security',
    severity: 'high',
    rule: 'innerHTML-assignment',
    message: 'innerHTML assignment — XSS risk, use textContent or sanitize',
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
  },
  {
    pattern:
      /(?:SELECT|INSERT|UPDATE|DELETE)\s+.*\+\s*(?:\w+|['"`])/gi,
    category: 'security',
    severity: 'critical',
    rule: 'sql-concatenation',
    message:
      'SQL string concatenation — use parameterized queries to prevent injection',
  },
  {
    pattern: /os\.system\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'os-system',
    message: 'os.system() — shell injection risk, use subprocess.run with shell=False',
    extensions: ['.py'],
  },
  {
    pattern: /subprocess\.(?:call|run|Popen)\s*\([^)]*shell\s*=\s*True/g,
    category: 'security',
    severity: 'high',
    rule: 'subprocess-shell',
    message: 'subprocess with shell=True — shell injection risk',
    extensions: ['.py'],
  },
  {
    pattern: /from\s+pickle\s+import|import\s+pickle/g,
    category: 'security',
    severity: 'high',
    rule: 'pickle-usage',
    message: 'pickle deserialization is unsafe with untrusted data — use JSON or msgpack',
    extensions: ['.py'],
  },
  {
    pattern: /(?:SELECT|INSERT|UPDATE|DELETE|FROM|WHERE).*\.format\s*\(/gi,
    category: 'security',
    severity: 'high',
    rule: 'sql-format-string',
    message: 'SQL with .format() — use parameterized queries to prevent injection',
    extensions: ['.py'],
  },
  {
    pattern: /\.\s*Exec\s*\(\s*["'`].*\+/g,
    category: 'security',
    severity: 'critical',
    rule: 'go-sql-concat',
    message: 'SQL concatenation in Exec — use parameterized queries',
    extensions: ['.go'],
  },
  {
    pattern: /unsafe\./g,
    category: 'security',
    severity: 'high',
    rule: 'rust-unsafe',
    message: 'unsafe block — minimize scope and document safety invariants',
    extensions: ['.rs'],
  },
  {
    pattern: /\{@html\s/g,
    category: 'security',
    severity: 'high',
    rule: 'svelte-raw-html',
    message: '{@html} renders unescaped HTML — XSS risk, sanitize first',
    extensions: ['.svelte'],
  },
  {
    pattern: /bind:(?:innerHTML|textContent)\s*=/g,
    category: 'security',
    severity: 'high',
    rule: 'svelte-bind-html',
    message: 'bind:innerHTML — XSS risk, sanitize content',
    extensions: ['.svelte'],
  },
  {
    pattern: /Statement\s*\w*\s*=|\.createStatement\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'java-raw-statement',
    message: 'Raw JDBC Statement — use PreparedStatement to prevent SQL injection',
    extensions: ['.java'],
  },
  {
    pattern: /(?:password|secret|api[_-]?key)\s*=\s*"[^"]+"/gi,
    category: 'security',
    severity: 'critical',
    rule: 'java-hardcoded-credential',
    message: 'Hardcoded credential — use environment variables or a secrets manager',
    extensions: ['.java', '.properties', '.yml', '.yaml'],
  },
  {
    pattern: /fmt\.Sprintf\s*\([^)]*%(?:s|v|d)[^)]*\+/g,
    category: 'security',
    severity: 'high',
    rule: 'go-format-injection',
    message: 'Dynamic format string — may enable format string injection',
    extensions: ['.go'],
  },
  {
    pattern: /http\.ListenAndServe\s*\(/g,
    category: 'security',
    severity: 'medium',
    rule: 'go-unencrypted-http',
    message: 'http.ListenAndServe without TLS — use ListenAndServeTLS in production',
    extensions: ['.go'],
  },
  {
    pattern: /std::mem::transmute/g,
    category: 'security',
    severity: 'critical',
    rule: 'rust-transmute',
    message: 'mem::transmute bypasses type system — use safe alternatives',
    extensions: ['.rs'],
  },
  {
    pattern: /\.as_ptr\(\)/g,
    category: 'security',
    severity: 'medium',
    rule: 'rust-raw-pointer',
    message: 'as_ptr() creates raw pointer — ensure lifetime safety',
    extensions: ['.rs'],
  },
  {
    pattern: /\beval\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'python-eval',
    message: 'eval() runs arbitrary code — use ast.literal_eval or JSON parsing',
    extensions: ['.py'],
  },
  {
    pattern: /\bexec\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'python-exec',
    message: 'exec() runs arbitrary code — avoid dynamic code execution',
    extensions: ['.py'],
  },
  {
    pattern: /from\s+yaml\s+import|import\s+yaml[\s;]/g,
    category: 'security',
    severity: 'medium',
    rule: 'python-yaml-load',
    message: 'yaml.load without Loader is unsafe — use yaml.safe_load',
    extensions: ['.py'],
  },
  {
    pattern: /hashlib\.md5\s*\(|hashlib\.sha1\s*\(/g,
    category: 'security',
    severity: 'medium',
    rule: 'python-weak-hash',
    message: 'MD5/SHA1 are cryptographically weak — use SHA-256+',
    extensions: ['.py'],
  },
  {
    pattern: /(?:readFile|readFileSync|createReadStream|open)\s*\([^)]*(?:\.\.\/?|req\.\w+|params\.\w+|query\.\w+)/g,
    category: 'security',
    severity: 'critical',
    rule: 'path-traversal',
    message: 'Path traversal risk (CWE-22) — validate and sanitize file paths',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /(?:fetch|axios\.(?:get|post|put|delete)|got|request)\s*\(\s*(?:req\.|params\.|query\.|args\.|user)/g,
    category: 'security',
    severity: 'high',
    rule: 'ssrf-risk',
    message: 'SSRF risk (CWE-918) — validate URLs against an allowlist',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /__proto__|Object\.assign\s*\(\s*\w+\s*,\s*(?:req\.|body\.|params\.|input)/g,
    category: 'security',
    severity: 'critical',
    rule: 'prototype-pollution',
    message: 'Prototype pollution risk — sanitize untrusted objects before merging',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /Math\.random\s*\(\)/g,
    category: 'security',
    severity: 'medium',
    rule: 'insecure-random',
    message: 'Math.random() is not cryptographically secure — use crypto.randomUUID() or crypto.getRandomValues()',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /jwt\.decode\s*\(/g,
    category: 'security',
    severity: 'high',
    rule: 'jwt-no-verify',
    message: 'jwt.decode() does not verify signature — use jwt.verify() instead',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /new\s+Function\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'new-function',
    message: 'new Function() enables code injection — use safe alternatives',
  },
  {
    pattern: /(?:res\.(?:json|send|status))\s*\([^)]*(?:err\.stack|error\.stack|\.stack|\.message)/g,
    category: 'security',
    severity: 'high',
    rule: 'error-info-leak',
    message: 'Error details in response leak internals — return generic messages to clients',
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'],
  },
  {
    pattern: /requests\.(?:get|post|put|delete|patch)\s*\([^)]*verify\s*=\s*False/g,
    category: 'security',
    severity: 'high',
    rule: 'python-requests-no-verify',
    message: 'SSL verification disabled — man-in-the-middle attack risk',
    extensions: ['.py'],
  },
  {
    pattern: /tempfile\.mktemp\s*\(/g,
    category: 'security',
    severity: 'high',
    rule: 'python-tempfile-insecure',
    message: 'tempfile.mktemp() has race condition — use mkstemp() or NamedTemporaryFile',
    extensions: ['.py'],
  },
  {
    pattern: /Runtime\.getRuntime\(\)\.exec\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'java-runtime-exec',
    message: 'Runtime.exec() — command injection risk, use ProcessBuilder with argument list',
    extensions: ['.java'],
  },
  {
    pattern: /math\/rand/g,
    category: 'security',
    severity: 'medium',
    rule: 'go-insecure-rand',
    message: 'math/rand is predictable — use crypto/rand for security-sensitive operations',
    extensions: ['.go'],
  },
  {
    pattern: /render_template_string\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'python-template-injection',
    message: 'render_template_string with user input enables SSTI (CWE-1336) — use render_template with files',
    extensions: ['.py'],
  },
  {
    pattern: /XMLReaderFactory\.createXMLReader|SAXParserFactory\.newInstance|DocumentBuilderFactory\.newInstance|XMLInputFactory\.newInstance/g,
    category: 'security',
    severity: 'critical',
    rule: 'java-xxe',
    message: 'XML parser without disabling external entities (CWE-611) — set FEATURE_EXTERNAL_GENERAL_ENTITIES to false',
    extensions: ['.java'],
  },
  {
    pattern: /new\s+ObjectInputStream\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'java-deserialization',
    message: 'ObjectInputStream deserialization (CWE-502) — use allowlists or safe formats (JSON, protobuf)',
    extensions: ['.java'],
  },
  {
    pattern: /SpelExpressionParser|ExpressionParser\s*\(\s*\)|\.parseExpression\s*\(/g,
    category: 'security',
    severity: 'critical',
    rule: 'java-spel-injection',
    message: 'Spring Expression Language injection (CWE-917) — avoid evaluating user-controlled expressions',
    extensions: ['.java'],
  },
  {
    pattern: /\.newConfiguration\(\)|FreeMarkerConfigurationFactory|VelocityEngine\s*\(\)|OgnlContext|ActionContext\.getContext/g,
    category: 'security',
    severity: 'critical',
    rule: 'java-ssti',
    message: 'Template engine with user input (CWE-1336) — sandbox templates, never pass raw user input',
    extensions: ['.java'],
  },
  {
    pattern: /(?:redirect|sendRedirect|location\.href|window\.location)\s*(?:=|\()\s*(?:req\.|params\.|query\.|request\.getParameter)/g,
    category: 'security',
    severity: 'high',
    rule: 'open-redirect',
    message: 'Open redirect (CWE-601) — validate redirect URLs against an allowlist',
  },
  {
    pattern: /AES\/ECB\//g,
    category: 'security',
    severity: 'high',
    rule: 'weak-crypto-ecb',
    message: 'AES-ECB mode is insecure (CWE-327) — use AES-GCM or AES-CBC with HMAC',
    extensions: ['.java', '.kt', '.kts'],
  },
  {
    pattern: /ZipEntry|ZipInputStream|TarArchiveEntry/g,
    category: 'security',
    severity: 'high',
    rule: 'zip-slip',
    message: 'Archive extraction without path validation (CWE-22) — check for path traversal in entry names',
    extensions: ['.java', '.kt', '.kts', '.go'],
  },
  {
    pattern: /XPathFactory\.newInstance|XPath\.compile|xpath\.evaluate/g,
    category: 'security',
    severity: 'high',
    rule: 'xpath-injection',
    message: 'XPath query with potential user input (CWE-643) — use parameterized XPath or validate input',
    extensions: ['.java'],
  },
  {
    pattern: /management\.endpoints\.web\.exposure\.include\s*=\s*\*|@EnableActuator/g,
    category: 'security',
    severity: 'high',
    rule: 'java-actuator-exposure',
    message: 'Spring Actuator exposed (CWE-200) — restrict endpoints and require authentication',
    extensions: ['.java', '.properties', '.yml', '.yaml'],
  },
  {
    pattern: /goja\.New\s*\(\)|otto\.New\s*\(\)/g,
    category: 'security',
    severity: 'high',
    rule: 'go-dynamic-code-exec',
    message: 'Dynamic code execution via JS engine (CWE-94) — sandbox execution and validate input',
    extensions: ['.go'],
  },
];
