import { mkdirSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type { ScanReport } from '../src/scanner.js';
import { formatReport, writeReport } from '../src/reporter.js';

function makeTempDir(): string {
  const dir = join(tmpdir(), `forge-rpt-${Date.now()}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

function makeReport(overrides: Partial<ScanReport> = {}): ScanReport {
  return {
    score: 85,
    grade: 'B',
    filesScanned: 10,
    findings: [
      {
        rule: 'empty-catch',
        severity: 'high',
        category: 'error-handling',
        message: 'Empty catch block swallows errors',
        file: 'src/app.ts',
        line: 42,
      },
      {
        rule: 'console-log',
        severity: 'low',
        category: 'engineering',
        message: 'Remove console.log before shipping',
        file: 'src/utils.ts',
        line: 7,
      },
    ],
    summary: [
      { category: 'error-handling', count: 1, critical: 0, high: 1 },
      { category: 'engineering', count: 1, critical: 0, high: 0 },
    ],
    topFiles: [
      { file: 'src/app.ts', count: 1, worst: 'high' },
    ],
    ...overrides,
  };
}

describe('formatReport — JSON', () => {
  it('outputs valid JSON with all fields', () => {
    const report = makeReport();
    const output = formatReport(report, 'json');
    const parsed = JSON.parse(output);
    expect(parsed.score).toBe(85);
    expect(parsed.grade).toBe('B');
    expect(parsed.findings).toHaveLength(2);
  });

  it('pretty-prints with 2-space indent', () => {
    const output = formatReport(makeReport(), 'json');
    expect(output).toContain('  "score"');
  });
});

describe('formatReport — markdown', () => {
  it('includes grade icon and score header', () => {
    const md = formatReport(makeReport(), 'markdown');
    expect(md).toContain('**Grade B**');
    expect(md).toContain('Score **85**/100');
    expect(md).toContain('10 files scanned');
  });

  it('shows critical issues table for high findings', () => {
    const md = formatReport(makeReport(), 'markdown');
    expect(md).toContain('Critical Issues');
    expect(md).toContain('`empty-catch`');
    expect(md).toContain('src/app.ts:42');
  });

  it('shows improvements section for low findings', () => {
    const md = formatReport(makeReport(), 'markdown');
    expect(md).toContain('Improvements');
    expect(md).toContain('`console-log`');
  });

  it('shows category breakdown', () => {
    const md = formatReport(makeReport(), 'markdown');
    expect(md).toContain('Category Breakdown');
    expect(md).toContain('Error Handling');
    expect(md).toContain('Engineering');
  });

  it('shows hot files section', () => {
    const md = formatReport(makeReport(), 'markdown');
    expect(md).toContain('Hot Files');
    expect(md).toContain('`src/app.ts`');
  });

  it('shows recommendations when findings exist', () => {
    const md = formatReport(makeReport(), 'markdown');
    expect(md).toContain('Recommendations');
    expect(md).toContain('high-priority');
  });

  it('shows strengths for clean projects', () => {
    const md = formatReport(
      makeReport({ summary: [], topFiles: [], findings: [] }),
      'markdown',
    );
    expect(md).toContain('Strengths');
    expect(md).toContain('No anti-patterns');
    expect(md).not.toContain('Critical Issues');
    expect(md).not.toContain('Improvements');
  });

  it('truncates at 15 critical findings', () => {
    const findings = Array.from({ length: 20 }, (_, i) => ({
      rule: `rule-${i}`,
      severity: 'critical' as const,
      category: 'security' as const,
      message: `Finding ${i}`,
      file: `src/file${i}.ts`,
      line: i + 1,
    }));
    const md = formatReport(
      makeReport({ findings }),
      'markdown',
    );
    expect(md).toContain('more critical/high');
  });

  it('includes version footer', () => {
    const md = formatReport(makeReport(), 'markdown');
    expect(md).toContain('Generated by forge-ai-init v0.25.0');
  });

  it('uses correct grade icons', () => {
    expect(formatReport(
      makeReport({ grade: 'A', score: 95 }), 'markdown',
    )).toContain('🟢');
    expect(formatReport(
      makeReport({ grade: 'D', score: 45 }), 'markdown',
    )).toContain('🟠');
    expect(formatReport(
      makeReport({ grade: 'F', score: 20 }), 'markdown',
    )).toContain('🔴');
  });
});

describe('formatReport — SARIF', () => {
  it('outputs valid SARIF 2.1.0 structure', () => {
    const output = formatReport(makeReport(), 'sarif');
    const sarif = JSON.parse(output);
    expect(sarif.version).toBe('2.1.0');
    expect(sarif.$schema).toContain('sarif-schema-2.1.0');
    expect(sarif.runs).toHaveLength(1);
  });

  it('includes tool driver info', () => {
    const sarif = JSON.parse(formatReport(makeReport(), 'sarif'));
    const driver = sarif.runs[0].tool.driver;
    expect(driver.name).toBe('forge-ai-init');
    expect(driver.version).toBe('0.25.0');
  });

  it('maps findings to SARIF results', () => {
    const sarif = JSON.parse(formatReport(makeReport(), 'sarif'));
    const results = sarif.runs[0].results;
    expect(results).toHaveLength(2);
    expect(results[0].ruleId).toBe('empty-catch');
    expect(results[0].message.text).toBe(
      'Empty catch block swallows errors',
    );
  });

  it('maps severity to SARIF levels correctly', () => {
    const report = makeReport({
      findings: [
        {
          rule: 'r1',
          severity: 'critical',
          category: 'security',
          message: 'Critical',
          file: 'a.ts',
          line: 1,
        },
        {
          rule: 'r2',
          severity: 'high',
          category: 'security',
          message: 'High',
          file: 'b.ts',
          line: 2,
        },
        {
          rule: 'r3',
          severity: 'medium',
          category: 'engineering',
          message: 'Medium',
          file: 'c.ts',
          line: 3,
        },
        {
          rule: 'r4',
          severity: 'low',
          category: 'engineering',
          message: 'Low',
          file: 'd.ts',
          line: 4,
        },
      ],
    });
    const sarif = JSON.parse(formatReport(report, 'sarif'));
    const results = sarif.runs[0].results;
    expect(results[0].level).toBe('error');
    expect(results[1].level).toBe('error');
    expect(results[2].level).toBe('warning');
    expect(results[3].level).toBe('note');
  });

  it('includes physical location with line number', () => {
    const sarif = JSON.parse(formatReport(makeReport(), 'sarif'));
    const loc =
      sarif.runs[0].results[0].locations[0].physicalLocation;
    expect(loc.artifactLocation.uri).toBe('src/app.ts');
    expect(loc.region.startLine).toBe(42);
  });

  it('maps categories to SARIF rules', () => {
    const sarif = JSON.parse(formatReport(makeReport(), 'sarif'));
    const rules = sarif.runs[0].tool.driver.rules;
    expect(rules).toHaveLength(2);
    expect(rules[0].id).toBe('error-handling');
    expect(rules[1].id).toBe('engineering');
  });
});

describe('writeReport', () => {
  let dir: string;

  beforeEach(() => {
    dir = makeTempDir();
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('writes JSON report to file', () => {
    const report = makeReport();
    const outPath = join(dir, 'report.json');
    writeReport(report, 'json', outPath);
    const content = readFileSync(outPath, 'utf-8');
    const parsed = JSON.parse(content);
    expect(parsed.score).toBe(85);
  });

  it('writes markdown report to file', () => {
    const outPath = join(dir, 'report.md');
    writeReport(makeReport(), 'markdown', outPath);
    const content = readFileSync(outPath, 'utf-8');
    expect(content).toContain('**Grade B**');
  });

  it('writes SARIF report to file', () => {
    const outPath = join(dir, 'report.sarif');
    writeReport(makeReport(), 'sarif', outPath);
    const content = readFileSync(outPath, 'utf-8');
    const sarif = JSON.parse(content);
    expect(sarif.version).toBe('2.1.0');
  });
});
