import type { DetectedStack, Tier } from '../types.js';
import { commonRules } from '../templates/rules/common.js';
import { typescriptRules } from '../templates/rules/typescript.js';
import { nextjsRules } from '../templates/rules/nextjs.js';
import { reactRules } from '../templates/rules/react.js';
import { nodeRules } from '../templates/rules/node.js';
import { pythonRules } from '../templates/rules/python.js';
import { vueRules } from '../templates/rules/vue.js';
import { expressRules } from '../templates/rules/express.js';
import { goRules } from '../templates/rules/go.js';
import { rustRules } from '../templates/rules/rust.js';
import { javaRules } from '../templates/rules/java.js';
import { kotlinRules } from '../templates/rules/kotlin.js';
import { svelteRules } from '../templates/rules/svelte.js';
import {
  aiGovernanceRules,
  aiAntiPatterns,
} from '../templates/rules/ai-governance.js';
import { scalabilityRules } from '../templates/rules/scalability.js';
import { migrationRules } from '../templates/rules/migration.js';

function quickReference(stack: DetectedStack): string {
  const lines: string[] = ['## Quick Reference', '', '```bash'];

  if (stack.devCommand) lines.push(`${stack.devCommand}`);
  if (stack.buildCommand) lines.push(`${stack.buildCommand}`);
  if (stack.testCommand) lines.push(`${stack.testCommand}`);
  if (stack.lintCommand) lines.push(`${stack.lintCommand}`);

  lines.push('```');
  return lines.join('\n');
}

function stackLabel(stack: DetectedStack): string {
  const parts: string[] = [];
  if (stack.framework) parts.push(stack.framework);
  parts.push(stack.language);
  if (stack.monorepo) parts.push('monorepo');
  return parts.join(' + ');
}

function frameworkRules(stack: DetectedStack): string {
  const sections: string[] = [];

  if (
    stack.language === 'typescript' ||
    stack.language === 'javascript'
  ) {
    if (stack.language === 'typescript') {
      sections.push(typescriptRules());
    }
  }

  switch (stack.framework) {
    case 'nextjs':
      sections.push(nextjsRules());
      sections.push(reactRules());
      break;
    case 'remix':
      sections.push(reactRules());
      break;
    case 'react':
      sections.push(reactRules());
      break;
    case 'vue':
    case 'nuxt':
      sections.push(vueRules());
      break;
    case 'express':
    case 'nestjs':
      sections.push(expressRules());
      sections.push(nodeRules());
      break;
    case 'fastapi':
    case 'django':
    case 'flask':
      sections.push(pythonRules());
      break;
    case 'svelte':
    case 'sveltekit':
      sections.push(svelteRules());
      break;
    default:
      if (stack.language === 'python') {
        sections.push(pythonRules());
      }
      if (
        stack.language === 'javascript' ||
        stack.language === 'typescript'
      ) {
        sections.push(nodeRules());
      }
      if (stack.language === 'go') {
        sections.push(goRules());
      }
      if (stack.language === 'rust') {
        sections.push(rustRules());
      }
      if (stack.language === 'java') {
        sections.push(javaRules());
      }
      if (stack.language === 'kotlin') {
        sections.push(kotlinRules());
      }
      break;
  }

  return sections.join('\n\n');
}

function enterpriseSection(): string {
  return `## Compliance
- Architecture Decision Records (ADRs) required for significant changes
- Security review required for auth, payment, PII handling
- Dependency updates reviewed weekly
- Audit logging for sensitive operations
- Data retention policies enforced in code`;
}

export function generateClaudeMd(
  stack: DetectedStack,
  tier: Tier,
  migrate?: boolean,
): string {
  const sections: string[] = [];

  sections.push(`# Project Rules`);
  sections.push('');
  sections.push(
    `> Generated by [forge-ai-init](https://github.com/Forge-Space/forge-ai-init) for ${stackLabel(stack)}`,
  );
  sections.push('');

  sections.push(quickReference(stack));
  sections.push('');
  sections.push(commonRules());
  sections.push('');
  sections.push(aiGovernanceRules());
  sections.push('');
  sections.push(aiAntiPatterns());
  sections.push('');
  sections.push(frameworkRules(stack));

  if (tier === 'standard' || tier === 'enterprise') {
    sections.push('');
    sections.push(scalabilityRules());
  }

  if (tier === 'enterprise') {
    sections.push('');
    sections.push(enterpriseSection());
  }

  if (migrate) {
    sections.push('');
    sections.push(migrationRules());
  }

  return sections.join('\n') + '\n';
}

export function generateCursorRules(
  stack: DetectedStack,
  tier: Tier,
  migrate?: boolean,
): string {
  const sections: string[] = [];

  sections.push(commonRules());
  sections.push('');
  sections.push(aiGovernanceRules());
  sections.push('');
  sections.push(aiAntiPatterns());
  sections.push('');
  sections.push(frameworkRules(stack));

  if (tier === 'standard' || tier === 'enterprise') {
    sections.push('');
    sections.push(scalabilityRules());
  }

  if (tier === 'enterprise') {
    sections.push('');
    sections.push(enterpriseSection());
  }

  if (migrate) {
    sections.push('');
    sections.push(migrationRules());
  }

  return sections.join('\n') + '\n';
}

export function generateWindsurfRules(
  stack: DetectedStack,
  tier: Tier,
  migrate?: boolean,
): string {
  return generateCursorRules(stack, tier, migrate);
}

export function generateCopilotInstructions(
  stack: DetectedStack,
  tier: Tier,
  migrate?: boolean,
): string {
  return (
    `# Copilot Instructions\n\n` +
    generateCursorRules(stack, tier, migrate)
  );
}
