import { writeFileSync } from 'node:fs';
import pc from 'picocolors';
import { assessProject, type AssessmentReport } from '../assessor.js';
import { writeReport, type ReportFormat } from '../reporter.js';
import type { DetectedStack } from '../types.js';
import { gradeColor, severityColor } from './ui.js';
import { getCliVersion } from './parse.js';

function formatAssessMarkdown(report: AssessmentReport): string {
  const lines: string[] = [];
  lines.push('# forge-ai-init Assessment Report');
  lines.push('');
  lines.push(
    `**Grade:** ${report.overallGrade} | **Score:** ${report.overallScore}/100 | **Files:** ${report.filesScanned}`,
  );
  lines.push(
    `**Strategy:** ${report.migrationStrategy} | **Readiness:** ${report.migrationReadiness}`,
  );
  lines.push('');
  lines.push('## Categories');
  lines.push('');
  lines.push('| Category | Score | Grade | Findings | Critical |');
  lines.push('|----------|-------|-------|----------|----------|');
  for (const cat of report.categories) {
    lines.push(`| ${cat.category} | ${cat.score}/100 | ${cat.grade} | ${cat.findings} | ${cat.critical} |`);
  }
  lines.push('');

  const critical = report.findings.filter((f) => f.severity === 'critical' || f.severity === 'high');
  if (critical.length > 0) {
    lines.push('## Critical & High Findings');
    lines.push('');
    for (const f of critical.slice(0, 30)) {
      lines.push(`- **${f.severity}** [${f.category}] ${f.title}`);
      if (f.file) lines.push(`  ${f.file}`);
    }
    lines.push('');
  }

  lines.push(`*Generated by forge-ai-init v${getCliVersion()}*`);
  lines.push('');
  return lines.join('\n');
}

export function runAssessCommand(
  projectDir: string,
  stack: DetectedStack,
  asJson: boolean,
  outputPath?: string,
  format?: string,
): void {
  const report = assessProject(projectDir, stack);

  if (outputPath) {
    const fmt = (format ?? 'json') as ReportFormat;
    const content = fmt === 'markdown' ? formatAssessMarkdown(report) : JSON.stringify(report, null, 2);
    writeFileSync(outputPath, content, 'utf-8');
    console.log(`  ${pc.green('✓')} Assessment written to ${outputPath} (${fmt})`);
    return;
  }

  if (asJson) { console.log(JSON.stringify(report, null, 2)); return; }
  if (format) {
    console.log(format === 'markdown' ? formatAssessMarkdown(report) : JSON.stringify(report, null, 2));
    return;
  }

  console.log('');
  console.log(`  ${pc.bold(pc.magenta('forge-ai-init assess'))} — Migration Health Assessment`);
  console.log('');
  console.log(`  ${pc.dim('Project:')} ${projectDir}`);
  console.log(`  ${pc.dim('Files scanned:')} ${report.filesScanned}`);
  console.log('');

  for (const cat of report.categories) {
    const gradeStr = gradeColor(cat.grade);
    const critLabel = cat.critical > 0 ? pc.red(` (${cat.critical} critical)`) : '';
    console.log(
      `  ${pc.bold(cat.category)} ${pc.dim('─'.repeat(22 - cat.category.length))} ${gradeStr} ${cat.score}/100${critLabel}`,
    );
  }
  console.log('');
  console.log(pc.bold(`  Overall: ${gradeColor(report.overallGrade)}  Score: ${report.overallScore}/100`));
  console.log(`  ${pc.dim('Strategy:')} ${pc.cyan(report.migrationStrategy)}`);
  console.log(
    `  ${pc.dim('Readiness:')} ${report.migrationReadiness === 'ready' ? pc.green('ready') : report.migrationReadiness === 'needs-work' ? pc.yellow('needs-work') : pc.red('high-risk')}`,
  );
  console.log('');

  const critical = report.findings.filter((f) => f.severity === 'critical' || f.severity === 'high');
  if (critical.length > 0) {
    console.log(`  ${pc.bold('Top issues:')}`);
    for (const f of critical.slice(0, 10)) {
      console.log(`    ${severityColor(f.severity)} ${f.title}`);
      if (f.file) console.log(`      ${pc.dim(f.file)}`);
    }
    if (critical.length > 10) console.log(pc.dim(`    ... and ${critical.length - 10} more`));
    console.log('');
  }

  void writeReport; // unused here but keep import for future use
}
