import { writeFileSync } from 'node:fs';
import type { ScanReport } from './scanner.js';

export type ReportFormat = 'json' | 'markdown' | 'sarif';

function toMarkdown(report: ScanReport): string {
  const lines: string[] = [];

  lines.push('# forge-ai-init Scan Report');
  lines.push('');
  lines.push(
    `**Grade:** ${report.grade} | **Score:** ${report.score}/100 | **Files:** ${report.filesScanned}`,
  );
  lines.push('');

  if (report.summary.length > 0) {
    lines.push('## Category Summary');
    lines.push('');
    lines.push(
      '| Category | Count | Critical | High |',
    );
    lines.push('|----------|-------|----------|------|');
    for (const cat of report.summary) {
      lines.push(
        `| ${cat.category} | ${cat.count} | ${cat.critical} | ${cat.high} |`,
      );
    }
    lines.push('');
  }

  if (report.topFiles.length > 0) {
    lines.push('## Top Files');
    lines.push('');
    lines.push('| File | Findings | Worst |');
    lines.push('|------|----------|-------|');
    for (const f of report.topFiles) {
      lines.push(`| ${f.file} | ${f.count} | ${f.worst} |`);
    }
    lines.push('');
  }

  const critical = report.findings.filter(
    f => f.severity === 'critical' || f.severity === 'high',
  );
  if (critical.length > 0) {
    lines.push('## Critical & High Findings');
    lines.push('');
    for (const f of critical.slice(0, 30)) {
      lines.push(
        `- **${f.severity}** \`${f.rule}\` — ${f.file}:${f.line}`,
      );
      lines.push(`  ${f.message}`);
    }
    if (critical.length > 30) {
      lines.push(`- ... and ${critical.length - 30} more`);
    }
    lines.push('');
  }

  lines.push(
    `*Generated by forge-ai-init v${getVersion()}*`,
  );
  lines.push('');

  return lines.join('\n');
}

function toSarif(report: ScanReport): string {
  const sarif = {
    $schema:
      'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json',
    version: '2.1.0',
    runs: [
      {
        tool: {
          driver: {
            name: 'forge-ai-init',
            version: getVersion(),
            rules: report.summary.map(cat => ({
              id: cat.category,
              shortDescription: {
                text: `${cat.category} findings`,
              },
            })),
          },
        },
        results: report.findings.map(f => ({
          ruleId: f.rule,
          level: sarifLevel(f.severity),
          message: { text: f.message },
          locations: [
            {
              physicalLocation: {
                artifactLocation: { uri: f.file },
                region: {
                  startLine: f.line,
                },
              },
            },
          ],
        })),
      },
    ],
  };

  return JSON.stringify(sarif, null, 2);
}

function sarifLevel(
  severity: string,
): 'error' | 'warning' | 'note' {
  switch (severity) {
    case 'critical':
    case 'high':
      return 'error';
    case 'medium':
      return 'warning';
    default:
      return 'note';
  }
}

function getVersion(): string {
  return '0.11.0';
}


export function formatReport(
  report: ScanReport,
  format: ReportFormat,
): string {
  switch (format) {
    case 'json':
      return JSON.stringify(report, null, 2);
    case 'markdown':
      return toMarkdown(report);
    case 'sarif':
      return toSarif(report);
  }
}

export function writeReport(
  report: ScanReport,
  format: ReportFormat,
  outputPath: string,
): void {
  const content = formatReport(report, format);
  writeFileSync(outputPath, content, 'utf-8');
}
